### ISSUE TITLE
Implement and test loop command

### ISSUE THREAD

**Issue by mateusz2173** [WebSoftDevs/MusicBot#28]
Syntax: `!loop [optionalAmount]` - loops current queue given amount of times

## Examples:

Input:

- `queue = [song1, song2, song3, song4]`
- `currentSong = null` (Music not playing)
- `arg = 2`

Output:
- `queue = [song1, song2, song3, song4, 
                    song1, song2, song3, song4, 
                    song1, song2, song3, song4]`

<hr>

Input:
- `queue = [song1, song2, song3, song4]`
- `currentSong != null` (Music currently playing)
- `arg = 2`

Output:
- `queue = [song1, song2, song3, song4, currentSong, song1, song2, song3, song4, currentSong, song1, song2, song3, song4]`

## Important notes:
- Default argument should be 1
- Queue length should not exceed 1000
- Loop has no effect on empty queue with currentSong = null
- Loop has no effect when passing invalid argument (non-positive number, or not number argument - parsing is required)
- Loop command should print at least one message using message.reply in ANY case

**Comment by xNykram** [comment]
partially done, need to rewrite code for tests

**Comment by mateusz2173** [comment]
We can leave tests for now. If the command is done merge changes with dev

**Comment by xNykram** [comment]
I'll check how it works locally and will deploy.

**Comment by xNykram** [comment]
https://github.com/WebSoftDevs/MusicBot/pull/63/

**Comment by mateusz2173** [comment]
Done

**Comment by xNykram** [comment]
Changes available on prod.
