### ISSUE TITLE
Add multithreading

### ISSUE THREAD

**Issue by mateusz2173** [WebSoftDevs/MusicBot#39]
as above. Bot stops playing for instance when command `!play` is fired. It can be fixed using multithreading.

**Comment by mateusz2173** [comment]
As i figured, there is no multithreading in JS/TS. 
There is something called "workers" which i will look to.
Also I'll read some open-source code of similar projects to figure out the solution.

**Comment by xNykram** [comment]
Any updates? Maybe should we close it and focus on SoftManager?

**Comment by mateusz2173** [comment]
Closing for now
