### ISSUE TITLE
Interface for adding/displaying database records

### ISSUE THREAD

**Issue by xNykram** [WebSoftDevs/MusicBot#55]
We need a separate application that will display records from the database and also allow us to edit the data. This would be useful, for example, when we want to edit a changelog entry. Maybe [SoftManager ](https://github.com/WebSoftDevs/SoftManager) can handle it?

**Comment by mateusz2173** [comment]
I made issue in SoftManager

https://github.com/WebSoftDevs/SoftManager/issues/1
