### ISSUE TITLE
Store logs in database

### ISSUE THREAD

**Issue by xNykram** [WebSoftDevs/MusicBot#56]
Log all failure tasks into database

- [x] Create table for logs
- [x] Insert logs to db via function in app

**Comment by xNykram** [comment]
@mateusz2173 
I need a list of actions to be monitored. Example: When the bot joins/leave the channel etc..

**Comment by xNykram** [comment]
I put this in index.ts in error handling section, it should works.

**Comment by mateusz2173** [comment]
> @mateusz2173 I need a list of actions to be monitored. Example: When the bot joins/leave the channel etc..

For now let it be:

- Bot **first** join on the server (that is list of servers where bot has ever been)
- Any errors thrown in index.ts
