### ISSUE TITLE
Add healtcheck command

### ISSUE THREAD

**Issue by xNykram** [WebSoftDevs/MusicBot#58]
We need to know if the application has a connection to the database, my idea is to create a hidden healtcheck command which will query the database and display a message if the connection exists. Mentioned command can help us diagnose any kind of issues.

**Comment by mateusz2173** [comment]
The idea is OK. Maybe something like `!status` command? It could also display some info like:

- How long bot is running
- Connection latency
- available RAM
- etc

**Comment by xNykram** [comment]
Command is ready for implementation.

![image](https://user-images.githubusercontent.com/55030025/171730004-76aa6d5d-4107-4a06-9829-bc4cfa87bbb4.png)

@mateusz2173 
Should I add something else?

**Comment by mateusz2173** [comment]
Nope, seems fine!

**Comment by xNykram** [comment]
Changes available on prod.
